# ["mixtral-8x7b-32768", "llama3-8b-8192", "llama3-70b-8192", "deepseek-coder", "deepseek-coder-33b", "gemma-7b-it"]
llms:
  information_supervisor:
    provider: groq
    model: deepseek-r1-distill-llama-70b 
  source_code:
    provider: groq
    model: deepseek-r1-distill-llama-70b  # Options: 
    #temperature: 0.7
  information_git:
    provider: groq
    model: deepseek-r1-distill-llama-70b 
  information_github:
    provider: groq
    model: deepseek-r1-distill-llama-70b 
  information_docs:
    provider: groq
    model: deepseek-r1-distill-llama-70b 
  response:
    provider: groq
    model: deepseek-r1-distill-llama-70b 
datasource:
  database:
    